Repository Santa-Application/App, pull requests merged in 2021-04, with the labels that each got.

#2 feat: Set client side and server side settings
  .gitignore
  Server/config/index.js
  Server/index.js
  Server/routes/auth.js
  Server/routes/index.js
  Server/utils/s3.js
  Server/utils/validation.js
  client/.storybook/main.js
  client/.storybook/preview.js
  client/jsconfig.json
  client/package.json
  client/src/App/App.css
  client/src/App/App.js
  client/src/App/App.test.js
  client/src/index.css
  client/src/index.js
  client/src/reportWebVitals.js
  client/src/setupTests.js
  client/src/stories/Button.js
  client/src/stories/Button.stories.js
  client/src/stories/Header.js
  client/src/stories/Header.stories.js
  client/src/stories/Introduction.stories.mdx
  client/src/stories/Page.js
  client/src/stories/Page.stories.js
  client/src/stories/assets/code-brackets.svg
  client/src/stories/assets/colors.svg
  client/src/stories/assets/comments.svg
  client/src/stories/assets/direction.svg
  client/src/stories/assets/flow.svg
  client/src/stories/assets/plugin.svg
  client/src/stories/assets/repo.svg
  client/src/stories/assets/stackalt.svg
  client/src/stories/button.css
  client/src/stories/header.css
  client/src/stories/page.css
Labels: Settings

#3 docs: Update README.md
  README.md
Labels: documentation

#6 feat: Add dependencies
  client/package.json
Labels: Settings

#7 fix: Fix gitignore
  .gitignore
  client/public/favicon.ico
  client/public/index.html
  client/public/logo192.png
  client/public/logo512.png
  client/public/manifest.json
  client/public/robots.txt
Labels: bug

#12 feat: Add eslint-prettier
  client/.eslintrc.json
  client/.prettierrc
  client/package.json
  client/src/App/App.css
  client/src/App/App.js
Labels: Settings

#13 Create variable colors
  client/.eslintrc.json
  client/package.json
  client/src/styles/variables.scss
Labels: style

#16 feat: Complete Button component
  client/src/components/Button/Button.js
  client/src/components/Button/Button.module.scss
  client/src/components/Button/Button.stories.js
  client/src/components/Icon/Icon.js
  client/src/components/Icon/Icon.module.scss
  client/src/components/Icon/Icon.stories.js
  client/src/index.css
  client/src/index.js
Labels: component

#19 feat: Create Input component , style: Import common.scss and variable.scss files at index.scss
  client/src/components/Input/Input.js
  client/src/components/Input/Input.module.scss
  client/src/components/Input/Input.stories.js
  client/src/styles/index.scss
Labels: component

#24 docs: Fix eslint setting
  client/.eslintrc.json
Labels: Settings

#25 update: Add Icon component
  client/src/components/Button/Button.js
  client/src/components/Button/Button.stories.js
  client/src/components/Icon/Icon.js
  client/src/components/Icon/Icon.module.scss
  client/src/components/Icon/Icon.stories.js
  client/src/components/Icon/assets/calendar.svg
  client/src/components/Icon/assets/close.svg
  client/src/components/Icon/assets/edit.svg
  client/src/components/Icon/assets/female.svg
  client/src/components/Icon/assets/gender-both.svg
  client/src/components/Icon/assets/goToBack.svg
  client/src/components/Icon/assets/like-false.svg
  client/src/components/Icon/assets/like-true.svg
  client/src/components/Icon/assets/logout.svg
  client/src/components/Icon/assets/male.svg
  client/src/components/Icon/assets/member.svg
  client/src/components/Icon/assets/menu.svg
  client/src/components/Icon/assets/mountain-level1.svg
  client/src/components/Icon/assets/mountain-level2.svg
  client/src/components/Icon/assets/mountain-level3.svg
  client/src/components/Icon/assets/select-close.svg
  client/src/components/Icon/assets/select-open.svg
Labels: component, storybook

#26 docs: Resolve ESlint and prettier problems
  client/.eslintrc.json
  client/.prettierrc
  client/src/components/Icon/Icon.js
Labels: Settings, bug

#27 style: Add flex mixin
  client/src/components/Input/Input.stories.js
  client/src/styles/index.scss
  client/src/styles/mixin.scss
Labels: style

#29 feat: Create SelectBox component
  client/src/components/SelectBox/SelectBox.js
  client/src/components/SelectBox/SelectBox.module.scss
  client/src/components/SelectBox/SelectBox.stories.js
  client/src/stories/Button.js
  client/src/stories/Button.stories.js
  client/src/stories/Header.js
  client/src/stories/Header.stories.js
  client/src/stories/Introduction.stories.mdx
  client/src/stories/Page.js
  client/src/stories/Page.stories.js
  client/src/stories/assets/code-brackets.svg
  client/src/stories/assets/colors.svg
  client/src/stories/assets/comments.svg
  client/src/stories/assets/direction.svg
  client/src/stories/assets/flow.svg
  client/src/stories/assets/plugin.svg
  client/src/stories/assets/repo.svg
  client/src/stories/assets/stackalt.svg
  client/src/stories/button.css
  client/src/stories/header.css
  client/src/stories/page.css
  client/src/styles/common.scss
Labels: component, storybook, style

#30 update: Add key property to mountain schema
  Server/models/Mountain.js
  Server/models/RegularPost.js
Labels: Small Adjustment, documentation

#32 update: Add Tag component and minor changes in Icon component
  client/src/components/Icon/Icon.js
  client/src/components/Icon/assets/mountain-level2.svg
  client/src/components/Tag/Tag.js
  client/src/components/Tag/Tag.module.scss
  client/src/components/Tag/Tag.stories.js
  client/src/components/index.js
Labels: Small Adjustment, component

#35 update: Add profileInformation component
  client/src/components/ProfileInformation/ProfileInformation.js
  client/src/components/ProfileInformation/ProfileInformation.module.scss
  client/src/components/ProfileInformation/ProfileInformation.stories.js
  client/src/components/Tag/Tag.js
  client/src/components/Tag/Tag.stories.js
  client/src/components/index.js
Labels: component, storybook, style

#42 Create components
  client/src/components/Button/Button.js
  client/src/components/Heading/Heading.js
  client/src/components/Heading/Heading.stories.js
  client/src/components/ProfileImage/ProfileImage.js
  client/src/components/ProfileImage/ProfileImage.module.scss
  client/src/components/ProfileImage/ProfileImage.stories.js
  client/src/components/RadioButton/RadioButton.stories.js
  client/src/components/RecruitPostCard/RecruitPostCard.js
  client/src/components/RecruitPostCard/RecruitPostCard.module.scss
  client/src/components/RecruitPostCard/RecruitPostCard.stories.js
  client/src/components/RegularPostCard/RegularPostCard.js
  client/src/components/RegularPostCard/RegularPostCard.module.scss
  client/src/components/RegularPostCard/RegularPostCard.stories.js
  client/src/components/Tag/Tag.js
  client/src/components/Tag/Tag.module.scss
  client/src/components/Textarea/Textarea.js
  client/src/components/Textarea/Textarea.module.scss
  client/src/components/Textarea/Textarea.stories.js
  client/src/components/index.js
  client/src/styles/variables.scss
  client/src/utils/index.js
  client/src/utils/postDate.js
Labels: component, storybook, style

#51 Select Date component
  client/src/components/Icon/Icon.js
  client/src/components/Input/Input.js
  client/src/components/Input/Input.stories.js
  client/src/components/SelectBox/SelectBox.js
  client/src/components/SelectDate/SelectDate.js
  client/src/components/SelectDate/SelectDate.module.scss
  client/src/components/SelectDate/SelectDate.stories.js
  client/src/styles/reset.scss
Labels: component, storybook, style

#62 docs: Fix arrow function sole parens error.
  client/src/reportWebVitals.js
Labels: bug

#65 update: Add profile Info Card
  client/src/components/ProfileInfoCard/ProfileInfoCard.js
  client/src/components/ProfileInfoCard/ProfileInfoCard.module.scss
  client/src/components/ProfileInfoCard/ProfileInfoCard.stories.js
  client/src/components/ProfileInformation/ProfileInformation.stories.js
Labels: component, storybook, style

#68 merge: Fix database schemas
  Server/models/RecruitPost.js
  Server/models/RegularPost.js
  client/src/components/ProfileInformation/ProfileInformation.stories.js
Labels: Database

#70 fix: Add attributes and modify DB schemas
  Server/models/RecruitPost.js
  Server/models/RegularPost.js
Labels: Database

#76 Create and update components and utilities and fix small problems
  client/src/components/Checkbox/Checkbox.js
  client/src/components/Checkbox/Checkbox.module.scss
  client/src/components/Checkbox/Checkbox.stories.js
  client/src/components/Heading/Heading.js
  client/src/components/Heading/Heading.stories.js
  client/src/components/LikeButton/LikeButton.js
  client/src/components/LikeButton/LikeButton.stories.js
  client/src/components/PostHeading/PostHeading.js
  client/src/components/PostHeading/PostHeading.stories.js
  client/src/components/ProfileImage/ProfileImage.module.scss
  client/src/components/ProfileImage/ProfileImage.stories.js
  client/src/components/RadioButton/RadioButton.js
  client/src/components/RadioButton/RadioButton.module.scss
  client/src/components/RadioButton/RadioButton.stories.js
  client/src/components/RecruitPostCard/RecruitPostCard.js
  client/src/components/RecruitPostCard/RecruitPostCard.module.scss
  client/src/components/RecruitPostCard/RecruitPostCard.stories.js
  client/src/components/RegularPostCard/RegularPostCard.js
  client/src/components/RegularPostCard/RegularPostCard.stories.js
  client/src/components/RoundedTextBox/RoundedTextBox.module.scss
  client/src/components/StatusOfApplicationBox/StatusOfApplicationBox.js
  client/src/components/StatusOfApplicationBox/StatusOfApplicationBox.module.scss
  client/src/components/StatusOfApplicationBox/StatusOfApplicationBox.stories.js
  client/src/components/Textarea/Textarea.js
  client/src/components/Textarea/Textarea.module.scss
  client/src/components/Textarea/Textarea.stories.js
  client/src/mock.js
  client/src/utils/index.js
  client/src/utils/propTypeInterface.js
Labels: Small Adjustment, component, refactor, storybook, style, utility

#77 feat: Create Range Slider component
  client/src/components/RangeSlider/RangeSlider.js
  client/src/components/RangeSlider/RangeSlider.module.scss
  client/src/components/RangeSlider/RangeSlider.stories.js
Labels: component, storybook, style

#78 merge: Modify Tag component
  client/src/components/Tag/Tag.js
  client/src/components/Tag/Tag.stories.js
Labels: component, refactor, storybook, style

#84 Add functions to Server, and got some mock datas
  Server/Data/mockMountainDatas.js
  Server/Data/top100Mountains.js
  Server/config/index.js
  Server/models/Mountain.js
  Server/models/RecruitPost.js
  Server/package.json
  Server/routes/auth.js
  Server/routes/index.js
  Server/routes/mountain.js
  Server/utils/getDatas.js
Labels: Database, Server

#82 Create containers and fix bugs and small problems
  client/src/App/App.js
  client/src/components/PostHeading/PostHeading.js
  client/src/components/ProfileImage/ProfileImage.stories.js
  client/src/components/PublisherInformation/PublisherInformation.js
  client/src/components/PublisherInformation/PublisherInformation.stories.js
  client/src/components/RecruitPostCard/RecruitPostCard.js
  client/src/components/RecruitPostCard/RecruitPostCard.module.scss
  client/src/components/RecruitPostCard/RecruitPostCard.stories.js
  client/src/components/RegularPostCard/RegularPostCard.js
  client/src/components/RegularPostCard/RegularPostCard.module.scss
  client/src/components/RegularPostCard/RegularPostCard.stories.js
  client/src/components/StatusOfApplicationBox/StatusOfApplicationBox.js
  client/src/components/StatusOfApplicationBox/StatusOfApplicationBox.stories.js
  client/src/components/index.js
  client/src/containers/RecruitPost/RecruitPost.js
  client/src/containers/RecruitPost/RecruitPost.module.scss
  client/src/containers/RecruitPostList/RecruitPostList.js
  client/src/containers/RecruitPostList/RecruitPostList.module.scss
  client/src/containers/RegularPost/RegularPost.js
  client/src/containers/RegularPost/RegularPost.module.scss
  client/src/containers/RegularPostList/RegularPostList.js
  client/src/containers/RegularPostList/RegularPostList.module.scss
  client/src/containers/index.js
  client/src/mock.js
  client/src/styles/reset.scss
  client/src/utils/api.js
  client/src/utils/index.js
  client/src/utils/propTypeInterface.js
Labels: Small Adjustment, bug, container, storybook, style, utility

#88 feat: Add Server side APIs
  Server/index.js
  Server/models/RecruitPost.js
  Server/models/RegularPost.js
  Server/models/User.js
  Server/routes/auth.js
  Server/routes/image.js
  Server/routes/index.js
  Server/routes/mountain.js
  Server/routes/recruitpost.js
  Server/routes/regularpost.js
Labels: Database, Server

#90 feat: Add MenuTab component
  client/src/components/MenuRadioButton/MenuRadioButton.js
  client/src/components/MenuRadioButton/MenuRadioButton.stories.js
  client/src/components/MenuTab/MenuTab.js
  client/src/components/MenuTab/MenuTab.module.scss
  client/src/components/MenuTab/MenuTab.stories.js
  client/src/components/index.js
  client/src/utils/tabhandlers.js
Labels: component, storybook, style

#89 Fix components and add oultline, font, box shadow style mixin
  client/src/components/Button/Button.module.scss
  client/src/components/Checkbox/Checkbox.js
  client/src/components/Checkbox/Checkbox.module.scss
  client/src/components/Checkbox/Checkbox.stories.js
  client/src/components/FileInput/FileInput.module.scss
  client/src/components/LikeButton/LikeButton.js
  client/src/components/LikeButton/LikeButton.stories.js
  client/src/components/NumberInput/NumberInput.module.scss
  client/src/components/PostHeading/PostHeading.module.scss
  client/src/components/ProfileImage/ProfileImage.js
  client/src/components/ProfileImage/ProfileImage.module.scss
  client/src/components/ProfileImage/ProfileImage.stories.js
  client/src/components/ProfileInfoCard/ProfileInfoCard.module.scss
  client/src/components/PublisherInformation/PublisherInformation.js
  client/src/components/PublisherInformation/PublisherInformation.module.scss
  client/src/components/RadioButton/RadioButton.js
  client/src/components/RadioButton/RadioButton.module.scss
  client/src/components/RadioButton/RadioButton.stories.js
  client/src/components/RangeSlider/RangeSlider.module.scss
  client/src/components/RecruitPostCard/RecruitPostCard.module.scss
  client/src/components/RegularPostCard/RegularPostCard.module.scss
  client/src/components/RoundedTextBox/RoundedTextBox.module.scss
  client/src/components/SelectBox/SelectBox.module.scss
  client/src/components/SelectDate/SelectDate.module.scss
  client/src/components/StatusOfApplicationBox/StatusOfApplicationBox.js
  client/src/components/StatusOfApplicationBox/StatusOfApplicationBox.module.scss
  client/src/components/Tag/Tag.module.scss
  client/src/components/Textarea/Textarea.js
  client/src/components/Textarea/Textarea.module.scss
  client/src/components/Textarea/Textarea.stories.js
  client/src/containers/RegularPost/RegularPost.module.scss
  client/src/styles/common.scss
  client/src/styles/mixin.scss
  client/src/styles/variables.scss
Labels: Small Adjustment, documentation, style

#92 feat: Add formik library and change variables in scss
  client/package.json
  client/src/components/MenuTab/MenuTab.module.scss
Labels: Settings, style

#96 feat: Modify Logo and Server recruitpost API
  Server/models/RecruitPost.js
  Server/routes/auth.js
  Server/routes/recruitpost.js
  client/src/components/Header/Header.js
  client/src/components/Header/Header.module.scss
  client/src/components/Header/Header.stories.js
  client/src/components/Logo/Logo.js
  client/src/components/Logo/Logo.stories.js
  client/src/components/Logo/assets/LogoBlack.svg
  client/src/components/Logo/assets/LogoWhite.svg
  client/src/components/MenuTab/MenuTab.js
  client/src/components/MenuTab/MenuTab.stories.js
  client/src/components/index.js
Labels: Server, component

#97 feat: Create Header component
  Server/routes/recruitpost.js
  client/src/components/Header/Header.js
  client/src/components/Header/Header.module.scss
  client/src/components/Logo/Logo.stories.js
Labels: Server, component

#99 feat: Create Form Item component and Improve Form-related components
  client/src/components/FileInput/FileInput.js
  client/src/components/FormItem/FormItem.js
  client/src/components/FormItem/FormItem.module.scss
  client/src/components/NumberInput/NumberInput.js
  client/src/components/NumberInput/NumberInput.stories.js
  client/src/components/RangeSlider/RangeSlider.js
  client/src/components/SelectBox/SelectBox.js
  client/src/components/SelectDate/SelectDate.js
  client/src/components/SelectDate/SelectDate.module.scss
Labels: component, style

#101 update: Add HomePage and Router settings
  Server/routes/recruitpost.js
  client/src/App/App.js
  client/src/components/Logo/Logo.js
  client/src/components/Logo/Logo.stories.js
  client/src/index.js
  client/src/pages/HomePage/HomePage.js
  client/src/pages/HomePage/HomePage.module.scss
  client/src/pages/HomePage/HomePage.stories.mdx
  client/src/pages/index.js
  client/src/styles/pages/page.scss
  client/src/styles/variables.scss
Labels: page, storybook, style

#102 Create footer component and add variable color and mixin
  client/src/components/Footer/Footer.js
  client/src/components/Footer/Footer.module.scss
  client/src/components/Footer/Footer.stories.js
  client/src/components/PostHeading/PostHeading.module.scss
  client/src/components/RadioButton/RadioButton.js
  client/src/components/RadioButton/RadioButton.module.scss
  client/src/components/RegularPostCard/RegularPostCard.module.scss
  client/src/components/RoundedTextBox/RoundedTextBox.module.scss
  client/src/components/Textarea/Textarea.module.scss
  client/src/components/index.js
  client/src/containers/RecruitPost/RecruitPost.module.scss
  client/src/containers/RegularPost/RegularPost.module.scss
  client/src/styles/mixin.scss
  client/src/styles/variables.scss
Labels: component, storybook, style

#104 Create reducers and update components
  client/src/api/index.js
  client/src/api/recruitPostAPI.js
  client/src/api/regularPostAPI.js
  client/src/components/RecruitPostCard/RecruitPostCard.js
  client/src/components/RecruitPostDetail/RecruitPostDetail.js
  client/src/components/RecruitPostDetail/RecruitPostDetail.module.scss
  client/src/components/RecruitPostList/RecruitPostList.js
  client/src/components/RecruitPostList/RecruitPostList.module.scss
  client/src/components/RegularPostCard/RegularPostCard.js
  client/src/components/RegularPostDetail/RegularPostDetail.js
  client/src/components/RegularPostDetail/RegularPostDetail.module.scss
  client/src/components/RegularPostList/RegularPostList.js
  client/src/components/RegularPostList/RegularPostList.module.scss
  client/src/components/index.js
  client/src/containers/RecruitPost/RecruitPost.js
  client/src/containers/RecruitPostList/RecruitPostList.js
  client/src/containers/RegularPost/RegularPost.js
  client/src/containers/index.js
  client/src/redux/modules/index.js
  client/src/redux/modules/recruitPost.js
  client/src/redux/modules/regularPost.js
  client/src/redux/store.js
  client/src/utils/api.js
  client/src/utils/index.js
  client/src/utils/propTypeInterface.js
  client/src/utils/reduxUtils.js
Labels: component, feature, refactor, storybook, style, utility

#110 Create SingInForm container and Refactor form-related components.
  client/src/components/FileInput/FileInput.js
  client/src/components/FileInput/FileInput.stories.js
  client/src/components/FormItem/FormItem.js
  client/src/components/FormItem/FormItem.module.scss
  client/src/components/FormItem/FormItem.stories.js
  client/src/components/Input/Input.js
  client/src/components/NumberInput/NumberInput.js
  client/src/components/NumberInput/NumberInput.stories.js
  client/src/components/SelectDate/SelectDate.js
  client/src/containers/SignInForm/SignInForm.js
Labels: Small Adjustment, component, container, refactor, storybook, style

#119 feat: Add search function and Modify markup in SelectBox component
  client/src/components/Input/Input.js
  client/src/components/SelectBox/SelectBox.js
  client/src/components/SelectBox/SelectBox.module.scss
Labels: feature, refactor, style

#117 Create search box and region select button component
  client/src/components/Icon/Icon.js
  client/src/components/Icon/assets/chungcheong.svg
  client/src/components/Icon/assets/gangwon.svg
  client/src/components/Icon/assets/gyeongsang.svg
  client/src/components/Icon/assets/jeju.svg
  client/src/components/Icon/assets/jeolla.svg
  client/src/components/Icon/assets/search.svg
  client/src/components/Icon/assets/seoul.svg
  client/src/components/RegionSelectButton/RegionSelectButton.js
  client/src/components/RegionSelectButton/RegionSelectButton.stories.js
  client/src/components/RoundedBox/RoundedBox.js
  client/src/components/RoundedBox/RoundedBox.module.scss
  client/src/components/RoundedBox/RoundedBox.stories.js
  client/src/components/SearchBox/SearchBox.js
  client/src/components/SearchBox/SearchBox.module.scss
  client/src/components/SearchBox/SearchBox.stories.js
  client/src/components/Tag/Tag.js
  client/src/components/index.js
Labels: component, documentation, storybook, style

#121 feat: Add yup library
  client/package.json
Labels: Settings

#122 Create validation schema utility
  client/src/utils/index.js
  client/src/utils/validationSchema.js
Labels: utility

#124 fix: Correct props for using formik form-related components.
  client/src/components/FileInput/FileInput.js
  client/src/components/NumberInput/NumberInput.js
  client/src/components/SelectBox/SelectBox.js
  client/src/components/SelectDate/SelectDate.js
  client/src/components/Textarea/Textarea.js
Labels: Small Adjustment

#125 fix: Fix import way and rename propTypeInterface to propTypeSchema
  client/src/components/PostHeading/PostHeading.js
  client/src/components/RecruitPostCard/RecruitPostCard.js
  client/src/components/RegularPostCard/RegularPostCard.js
  client/src/utils/propTypeSchema.js
  client/src/utils/validationSchema.js
Labels: bug, documentation

#132 modify: Make small adjustments to API codes
  Server/routes/index.js
  Server/routes/mountain.js
  Server/routes/recruitpost.js
  Server/routes/regularpost.js
  client/src/pages/Login/Login.js
  client/src/pages/Login/Login.module.scss
Labels: Server

#133 Create and update components
  client/public/favicon.ico
  client/src/components/FileInput/FileInput.js
  client/src/components/FormItem/FormItem.js
  client/src/components/Input/Input.module.scss
  client/src/components/RegionSelectButton/RegionSelectButton.js
  client/src/components/RegionSelectButton/RegionSelectButton.module.scss
  client/src/components/RegionSelectButtonGroup/RegionSelectButtonGroup.js
  client/src/components/RegionSelectButtonGroup/RegionSelectButtonGroup.module.scss
  client/src/components/RegionSelectButtonGroup/RegionSelectButtonGroup.stories.js
  client/src/components/RoundedBox/RoundedBox.js
  client/src/components/Tag/Tag.js
  client/src/components/Textarea/Textarea.js
  client/src/components/Textarea/Textarea.module.scss
  client/src/components/Textarea/Textarea.stories.js
  client/src/components/index.js
  client/src/containers/RegularPostForm/RegularPostForm.js
  client/src/containers/RegularPostForm/RegularPostForm.module.scss
  client/src/containers/index.js
  client/src/pages/GlobalRegularPostEditPage/GlobalRegularPostEditPage.js
  client/src/pages/GlobalRegularPostEditPage/GlobalRegularPostEditPage.module.scss
  client/src/pages/index.js
  client/src/styles/common.scss
  client/src/styles/mixin.scss
Labels: component, container, page, refactor, style

#136 feat: Add AuthReducer to redux store
  Server/routes/auth.js
  Server/routes/recruitpost.js
  Server/utils/tokenValidate.js
  client/src/api/authAPI.js
  client/src/api/index.js
  client/src/containers/RegisterForm/RegisterForm.js
  client/src/redux/modules/auth.js
  client/src/redux/modules/index.js
  client/src/utils/reduxUtils.js
Labels: feature

#138 Fix bugs form item elements are not working
  client/src/components/FormItem/FormItem.js
  client/src/components/Input/Input.js
Labels: bug

#139 feat: Create RecruitForm container and Fix props in form-related components.
  client/src/components/FileInput/FileInput.js
  client/src/components/FormItem/FormItem.js
  client/src/components/Input/Input.js
  client/src/components/NumberInput/NumberInput.js
  client/src/components/SelectBox/SelectBox.js
  client/src/components/SelectDate/SelectDate.js
  client/src/components/Textarea/Textarea.js
  client/src/containers/RecruitForm/RecruitForm.js
  client/src/data/top100Mountains.js
  client/src/utils/handler/formHandler.js
  client/src/utils/index.js
Labels: Database, bug, container, refactor, utility

#140 fix: Fix bug in form item, gender and hiking level select button components
  client/src/components/FormItem/FormItem.js
  client/src/components/GenderSelectButton/GenderSelectButton.js
  client/src/components/HikingLevelSelectButton/HikingLevelSelectButton.js
Labels: bug

#141 fix: Fix bug in recruit form container component
  client/src/containers/RecruitForm/RecruitForm.js
Labels: bug

#142 Fix bugs in select box and add redux store provider
  client/src/components/FileInput/FileInput.module.scss
  client/src/components/SelectBox/SelectBox.js
  client/src/components/SelectBox/SelectBox.module.scss
  client/src/containers/RecruitForm/RecruitForm.js
  client/src/containers/RegularPostForm/RegularPostForm.js
  client/src/containers/index.js
  client/src/index.js
  client/src/redux/modules/auth.js
  client/src/redux/modules/index.js
  client/src/styles/common.scss
Labels: Settings, bug, style

#143 add: Complete modification of Header component
  Server/models/User.js
  client/src/components/Header/Header.js
  client/src/components/Header/Header.module.scss
  client/src/components/Icon/Icon.js
  client/src/components/Icon/assets/mountains_nav.svg
  client/src/components/Icon/assets/profile_nav.svg
  client/src/components/Icon/assets/recruitposts_nav.svg
  client/src/components/Icon/assets/reviewposts_nav.svg
  client/src/components/Navigation/Navigation.js
  client/src/components/Navigation/Navigation.stories.js
  client/src/components/NavigationItem/NavigationItem.js
  client/src/components/NavigationItem/NavigationItem.module.scss
  client/src/components/NavigationItem/NavigationItem.stories.js
  client/src/components/Tag/Tag.js
  client/src/components/index.js
Labels: component, refactor

#144 feat: Change Server side codes
  Server/models/RecruitPost.js
  Server/models/RegularPost.js
  Server/routes/recruitpost.js
  Server/routes/regularpost.js
Labels: Database, Server

#146 feat: Add error message in form item component and Complete recruit form container.
  client/src/components/FormItem/FormItem.js
  client/src/components/FormItem/FormItem.module.scss
  client/src/components/NumberInput/NumberInput.js
  client/src/components/NumberInput/NumberInput.module.scss
  client/src/components/RadioButton/RadioButton.js
  client/src/components/RangeSlider/RangeSlider.js
  client/src/components/RangeSlider/RangeSlider.module.scss
  client/src/containers/RecruitForm/RecruitForm.js
  client/src/containers/RecruitForm/RecruitForm.module.scss
  client/src/utils/handler/formHandler.js
  client/src/utils/validationSchema.js
Labels: Small Adjustment, feature, style, utility

#147 Create recruit post list and detail pages and set router
  client/src/App/App.js
  client/src/App/App.module.scss
  client/src/api/recruitPostAPI.js
  client/src/api/regularPostAPI.js
  client/src/components/Header/Header.js
  client/src/components/Header/Header.module.scss
  client/src/components/Logo/Logo.js
  client/src/components/Navigation/Navigation.js
  client/src/components/Navigation/Navigation.module.scss
  client/src/components/NavigationItem/NavigationItem.module.scss
  client/src/components/PostHeading/PostHeading.js
  client/src/components/PublisherInformation/PublisherInformation.js
  client/src/components/RecruitPostCard/RecruitPostCard.js
  client/src/components/RecruitPostDetail/RecruitPostDetail.js
  client/src/components/RecruitPostList/RecruitPostList.js
  client/src/components/RoundedBox/RoundedBox.js
  client/src/components/StatusOfApplicationBox/StatusOfApplicationBox.js
  client/src/components/index.js
  client/src/containers/RecruitPostDetail/RecruitPostDetail.js
  client/src/containers/RecruitPostDetail/RecruitPostDetail.module.scss
  client/src/containers/RecruitPostList/RecruitPostList.js
  client/src/containers/RecruitPostList/RecruitPostList.module.scss
  client/src/containers/RegularPostDetail/RegularPostDetail.js
  client/src/containers/RegularPostDetail/RegularPostDetail.module.scss
  client/src/containers/RegularPostList/RegularPostList.js
  client/src/containers/RegularPostList/RegularPostList.module.scss
  client/src/containers/index.js
  client/src/mock.js
  client/src/pages/GlobalRegularPostEditPage/GlobalRegularPostEditPage.js
  client/src/pages/HomePage/HomePage.js
  client/src/pages/index.js
  client/src/redux/modules/recruitPost.js
  client/src/styles/common.scss
  client/src/utils/filterData.js
  client/src/utils/index.js
Labels: bug, component, container, feature, page, style, utility

#148 Add dispatch in Recruit form container
  client/src/containers/RecruitForm/RecruitForm.js
  client/src/containers/RegularPostForm/RegularPostForm.js
Labels: feature

#149 feat: Create PageNotFound page. 149ea6c
  client/src/pages/PageNotFound/PageNotFound.js
  client/src/pages/PageNotFound/PageNotFound.module.scss
Labels: page, style

#150 Develop
  Server/index.js
  Server/routes/auth.js
  Server/routes/recruitpost.js
  Server/routes/regularpost.js
  Server/uploads/083f66fc8c64b3aeb30431eacaa5a265
  Server/uploads/1be9232d3609464a87568276120d2e55
  Server/uploads/1c9179c4a5c69a844ad7c7b99fd6c588
  Server/uploads/2dee45fd245edf665fc0c739e7317882
  Server/uploads/3d59eef9b4a3ab1ce3a549a200f5d482
  Server/uploads/49669c69d2844de57f5ae53c3f4c17e3
  Server/uploads/4f3df4a827a6d208fa736865d2297d5b
  Server/uploads/5480f42d115b02f04733f6200b385562
  Server/uploads/71abff4f051fe05d9933c25862a112eb
  Server/uploads/7e54ce067757e2488c754ce86c821be8
  Server/uploads/93132a505757b74025b6971beb24a086
  Server/uploads/9dec7e0a3cfc027d633dc9eecbc6ba3a
  Server/uploads/b19783ba2a89a850f39285b8ad124a94
  Server/uploads/b8e2fe1cd983b7622e2e1618137d8924
  Server/uploads/c1c838888632954dbbbda3d4fdb4453e
  Server/uploads/eb8cccf624a2642e7e81139e766d699c
  Server/uploads/ef1d5e03872d1736dea649814794a8b5
  Server/uploads/ff42275fefe8fdec8c221f0d19df5ebb
  Server/uploads/ff9ebc0fe255ccac81164e942b1debbb
  Server/utils/validation.js
  client/src/App/App.js
  client/src/api/authAPI.js
  client/src/components/FileInput/FileInput.js
  client/src/components/Header/Header.js
  client/src/components/Header/Header.module.scss
  client/src/containers/RegisterForm/RegisterForm.js
  client/src/containers/RegisterForm/RegisterForm.module.scss
  client/src/containers/SignInForm/SignInForm.js
  client/src/containers/SignInForm/SignInForm.module.scss
  client/src/containers/SignInForm/SignInForm.stories.js
  client/src/pages/HomePage/HomePage.js
  client/src/pages/HomePage/HomePage.module.scss
  client/src/pages/Login/Login.js
  client/src/pages/Login/Login.module.scss
  client/src/pages/Register/Register.js
  client/src/pages/Register/Register.module.scss
  client/src/pages/index.js
  client/src/redux/modules/auth.js
  client/src/utils/reduxUtils.js
  client/src/utils/validationSchema.js
Labels: bug, page

#151 Update and fix bug
  client/src/App/App.js
  client/src/api/regularPostAPI.js
  client/src/components/Navigation/Navigation.js
  client/src/components/RegularPostCard/RegularPostCard.js
  client/src/containers/RecruitForm/RecruitForm.js
  client/src/containers/RecruitForm/RecruitForm.module.scss
  client/src/containers/RecruitPostDetail/RecruitPostDetail.js
  client/src/containers/RecruitPostList/RecruitPostList.js
  client/src/containers/RegularPostDetail/RegularPostDetail.js
  client/src/containers/RegularPostDetail/RegularPostDetail.module.scss
  client/src/containers/RegularPostList/RegularPostList.js
  client/src/utils/postDate.js
Labels: bug, component, container, style

#152 add: Save to session storage code
  client/src/api/authAPI.js
  client/src/redux/modules/auth.js
Labels: feature

#153 Set router, add event handlers, fix bugs, refactor and restyle
  client/src/App/App.js
  client/src/components/Header/Header.js
  client/src/containers/RecruitPostDetail/RecruitPostDetail.js
  client/src/containers/RegisterForm/RegisterForm.js
  client/src/containers/RegisterForm/RegisterForm.module.scss
  client/src/containers/RegularPostDetail/RegularPostDetail.js
  client/src/containers/RegularPostForm/RegularPostForm.js
  client/src/containers/RegularPostList/RegularPostList.js
  client/src/containers/SignInForm/SignInForm.js
  client/src/containers/SignInForm/SignInForm.module.scss
  client/src/pages/Login/Login.js
  client/src/pages/Login/Login.module.scss
  client/src/pages/Recruit/RecruitCreate.js
  client/src/pages/Recruit/RecruitDetail.js
  client/src/pages/Recruit/RecruitEdit.js
  client/src/pages/Recruit/RecruitList.js
  client/src/pages/Register/Register.js
  client/src/pages/Register/Register.module.scss
  client/src/pages/Regular/RegularCreate.js
  client/src/pages/Regular/RegularDetail.js
  client/src/pages/Regular/RegularEdit.js
  client/src/pages/Regular/RegularList.js
  client/src/pages/index.js
  client/src/styles/common.scss
Labels: bug, feature, page, refactor, style

#154 add: Server and Client auth features modification
  client/src/api/authAPI.js
  client/src/redux/modules/auth.js
Labels: Server

#155 Fix bugs(proceeding)
  client/public/LogoWhite.svg
  client/public/index.html
  client/public/logo192.png
  client/public/logo512.png
  client/public/manifest.json
  client/src/App/App.js
  client/src/api/recruitPostAPI.js
  client/src/api/regularPostAPI.js
  client/src/components/GenderSelectButton/GenderSelectButton.module.scss
  client/src/components/Header/Header.js
  client/src/components/Header/Header.module.scss
  client/src/components/HikingLevelSelectButton/HikingLevelSelectButton.module.scss
  client/src/components/RangeSlider/RangeSlider.js
  client/src/components/SelectBox/SelectBox.module.scss
  client/src/components/index.js
  client/src/containers/RecruitForm/RecruitForm.js
  client/src/containers/RecruitPostDetail/RecruitPostDetail.js
  client/src/containers/RecruitPostList/RecruitPostList.js
  client/src/containers/RegularPostDetail/RegularPostDetail.js
  client/src/containers/RegularPostDetail/RegularPostDetail.module.scss
  client/src/containers/RegularPostForm/RegularPostForm.js
  client/src/containers/RegularPostList/RegularPostList.js
  client/src/containers/SignInForm/SignInForm.js
  client/src/pages/PageNotFound/PageNotFound.js
  client/src/pages/Profile/UserRecruitList.js
  client/src/pages/Recruit/RecruitCreate.js
  client/src/pages/Regular/RegularCreate.js
  client/src/pages/index.js
  client/src/redux/modules/auth.js
  client/src/redux/modules/index.js
  client/src/redux/modules/recruitPost.js
  client/src/redux/modules/regularPost.js
  client/src/redux/store.js
  client/src/styles/common.scss
  client/src/styles/pages/page.scss
  client/src/utils/reduxUtils.js
  client/src/utils/validationSchema.js
Labels: Small Adjustment, bug, page, refactor, style

#156 fix: Fix typo
  client/src/pages/Profile/UserRecruitList.js
Labels: Small Adjustment, bug

#157 add: ProfileAPI and modify mountain API
  Server/index.js
  Server/routes/auth.js
  Server/routes/index.js
  Server/routes/mountain.js
  Server/routes/profile.js
  Server/routes/recruitpost.js
  Server/routes/regularpost.js
  client/src/api/index.js
  client/src/api/profileAPI.js
  client/src/redux/modules/auth.js
  client/src/redux/modules/profile.js
  client/src/utils/reduxUtils.js
Labels: Server

#158 feat: Create Mountain Reducer, Mountain page, Main page, and Add Search Mountain container in main page.
  client/src/App/App.js
  client/src/api/index.js
  client/src/api/mountainAPI.js
  client/src/components/MountainInfo/MountainInfo.js
  client/src/components/MountainInfo/MountainInfo.module.scss
  client/src/components/SearchBox/SearchBox.js
  client/src/components/SearchBox/SearchBox.module.scss
  client/src/components/SelectDate/SelectDate.js
  client/src/containers/MountainOverview/MountainOverview.js
  client/src/containers/MountainOverview/MountainOverview.module.scss
  client/src/containers/SearchMountain/SearchMountain.js
  client/src/pages/Main/Main.js
  client/src/pages/Mountain/Mountain.js
  client/src/pages/PageNotFound/PageNotFound.js
  client/src/pages/index.js
  client/src/redux/modules/index.js
  client/src/redux/modules/mountain.js
Labels: Server, Small Adjustment, bug, component, container, feature, page, style

#159 add: Change small mistakes and bugs and add carousel component
  Server/routes/mountain.js
  client/.storybook/preview.js
  client/package.json
  client/src/components/AreaCategory/AreaCategory.js
  client/src/components/AreaCategory/AreaCategory.module.scss
  client/src/components/AreaCategory/AreaCategory.stories.js
  client/src/components/AreaCategory/assets/강원도.svg
  client/src/components/AreaCategory/assets/경상도.svg
  client/src/components/AreaCategory/assets/서울경기.svg
  client/src/components/AreaCategory/assets/전라도.svg
  client/src/components/AreaCategory/assets/제주도.svg
  client/src/components/AreaCategory/assets/충청도.svg
  client/src/components/Carousel/Carousel.js
  client/src/components/Carousel/Carousel.module.scss
  client/src/components/Carousel/Carousel.stories.js
  client/src/components/CarouselSlider/CarouselSlider.js
  client/src/components/CarouselSlider/CarouselSlider.module.scss
  client/src/components/CarouselSlider/CarouselSlider.stories.js
  client/src/components/MountainCard/MountainCard.js
  client/src/components/MountainCard/MountainCard.module.scss
  client/src/components/MountainCard/MountainCard.stories.js
  client/src/components/index.js
  client/src/containers/SearchMountain/SearchMountain.js
Labels: bug, component, container, feature

#160 change: Modify Server side code
  Server/routes/auth.js
  Server/routes/recruitpost.js
  Server/routes/regularpost.js
  client/src/components/CarouselSlider/CarouselSlider.js
  client/src/components/CarouselSlider/CarouselSlider.module.scss
  client/src/components/CarouselSlider/CarouselSlider.stories.js
Labels: Server

#161 Fix bugs
  client/src/App/App.js
  client/src/api/recruitPostAPI.js
  client/src/components/Header/Header.js
  client/src/components/MenuTab/MenuTab.js
  client/src/components/MenuTab/MenuTab.module.scss
  client/src/components/Navigation/Navigation.js
  client/src/components/RecruitPostCard/RecruitPostCard.js
  client/src/components/SearchBox/SearchBox.js
  client/src/containers/RecruitForm/RecruitForm.js
  client/src/containers/RecruitForm/RecruitForm.module.scss
  client/src/containers/RecruitPostDetail/RecruitPostDetail.js
  client/src/containers/RecruitPostList/RecruitPostList.js
  client/src/containers/RecruitPostList/RecruitPostList.module.scss
  client/src/containers/RegularPostDetail/RegularPostDetail.js
  client/src/containers/RegularPostForm/RegularPostForm.js
  client/src/containers/RegularPostForm/RegularPostForm.module.scss
  client/src/containers/RegularPostList/RegularPostList.js
  client/src/containers/RegularPostList/RegularPostList.module.scss
  client/src/pages/Profile/Profile.js
  client/src/pages/Profile/UserRecruitList.js
  client/src/pages/index.js
  client/src/styles/common.scss
  client/src/styles/mixin.scss
  client/src/utils/filterData.js
  client/src/utils/reduxUtils.js
Labels: bug, documentation, style

#162 feat: Add search section in main page and Modify dispatch location in Mountain page.
  client/src/components/SearchBox/SearchBox.js
  client/src/components/SearchBox/SearchBox.module.scss
  client/src/containers/MountainOverview/MountainOverview.js
  client/src/containers/MountainOverview/MountainOverview.module.scss
  client/src/containers/SearchMountain/SearchMountain.js
  client/src/pages/Main/Main.js
  client/src/pages/Main/Main.module.scss
  client/src/pages/Mountain/Mountain.js
  client/src/pages/Mountain/Mountain.module.scss
Labels: Small Adjustment, page, style

#164 feat: Create Main Recruit container and Apply to Main page.
  client/src/containers/MainRecruit/MainRecruit.js
  client/src/containers/MainRecruit/MainRecruit.module.scss
  client/src/containers/MainRecruit/image/mainRecruit.png
  client/src/containers/SearchMountain/SearchMountain.js
  client/src/pages/Main/Main.js
  client/src/pages/Main/Main.module.scss
  client/src/pages/Main/image/mainSearch.png
Labels: Small Adjustment, container, style

#166 Create Loading component and Apply to Main page.
  client/src/components/LoadingIcon/LoadingIcon.js
  client/src/components/LoadingIcon/assets/spinner.svg
  client/src/containers/MainRecruit/MainRecruit.js
  client/src/containers/SearchMountain/SearchMountain.js
  client/src/pages/Main/Main.js
  client/src/pages/Mountain/Mountain.js
Labels: component, style

#167 feat: Modify loading location in mountain page and Add padding in Mou…
  client/src/containers/MountainOverview/MountainOverview.js
  client/src/containers/MountainOverview/MountainOverview.module.scss
  client/src/pages/Mountain/Mountain.js
Labels: Small Adjustment, style

#173 Fix bugs and merge components
  client/src/api/authAPI.js
  client/src/components/Header/Header.js
  client/src/components/ProfileInfoCard/ProfileInfoCard.js
  client/src/components/PublisherInformation/PublisherInformation.js
  client/src/containers/RecruitPostDetail/RecruitPostDetail.js
  client/src/containers/RegularPostDetail/RegularPostDetail.js
  client/src/containers/SignInForm/SignInForm.js
  client/src/pages/Profile/Profile.js
  client/src/pages/Recruit/RecruitEdit.js
  client/src/redux/modules/recruitPost.js
  client/src/utils/postDate.js
  client/src/utils/validationSchema.js
Labels: bug, documentation, utility

#174 add: Complete adding containers to MainPage
  .sass-cache/016df84409f763cadc74fe8180759fe7aa3b4321/CarouselSlider.module.scssc
  Server/models/RecruitPost.js
  Server/routes/auth.js
  Server/routes/recruitpost.js
  Server/routes/regularpost.js
  client/.storybook/preview.js
  client/package.json
  client/src/App/App.js
  client/src/components/Carousel/Carousel.stories.js
  client/src/components/CarouselSlider/CarouselSlider.js
  client/src/components/CarouselSlider/CarouselSlider.module.scss
  client/src/components/CarouselSlider/CarouselSlider.stories.js
  client/src/components/Icon/Icon.js
  client/src/components/Icon/Icon.stories.js
  client/src/components/Icon/assets/more.svg
  client/src/components/MountainCard/MountainCard.js
  client/src/components/RecruitPostCard/RecruitPostCard.js
  client/src/components/RecruitPostCard/RecruitPostCard.stories.js
  client/src/components/RegularPostCard/RegularPostCard.js
  client/src/components/RegularPostCard/RegularPostCard.stories.js
  client/src/components/index.js
  client/src/containers/Information/Information.js
  client/src/containers/Information/Information.module.scss
  client/src/containers/Information/Information.stories.js
  client/src/containers/ReviewCarousel/ReviewCarousel.js
  client/src/containers/ReviewCarousel/ReviewCarousel.module.scss
  client/src/containers/ReviewCarousel/ReviewCarousel.stories.js
  client/src/containers/index.js
  client/src/pages/Main/Main.js
  client/src/pages/Main/Main.module.scss
  client/src/pages/Main/image/mainSearch.jpg
  client/src/pages/Main/image/mainSearch.png
Labels: component, container, page

#175 docs: set useFindAndModify to false
  Server/index.js
Labels: Server, Settings

#176 set: Change imageURL expire time
  Server/utils/s3.js
Labels: Server, Settings

#177 feat: Add update function in Recruit form.
  client/src/api/recruitPostAPI.js
  client/src/containers/RecruitForm/RecruitForm.js
  client/src/utils/handler/formHandler.js
Labels: Small Adjustment, feature

#181 Set router, fix bugs and restyle mountain and profile page
  client/src/App/App.js
  client/src/components/MenuTab/MenuTab.module.scss
  client/src/components/MountainInfo/MountainInfo.module.scss
  client/src/components/Navigation/Navigation.js
  client/src/components/SearchBox/SearchBox.js
  client/src/containers/MountainOverview/MountainOverview.module.scss
  client/src/containers/RecruitForm/RecruitForm.js
  client/src/containers/RecruitPostList/RecruitPostList.js
  client/src/containers/RegularPostForm/RegularPostForm.js
  client/src/containers/RegularPostList/RegularPostList.js
  client/src/pages/Mountain/Mountain.js
  client/src/pages/Mountain/Mountain.module.scss
  client/src/pages/Profile/Profile.js
  client/src/styles/mixin.scss
Labels: bug, page, style

#182 Change path name of profile page for routing issue
  client/src/App/App.js
  client/src/components/PublisherInformation/PublisherInformation.js
  client/src/containers/RecruitForm/RecruitForm.js
  client/src/containers/RecruitPostDetail/RecruitPostDetail.js
  client/src/containers/RecruitPostList/RecruitPostList.js
  client/src/containers/RegularPostDetail/RegularPostDetail.js
  client/src/containers/RegularPostForm/RegularPostForm.js
  client/src/containers/RegularPostList/RegularPostList.js
  client/src/pages/Profile/Profile.js
Labels: Small Adjustment, bug

#183 fix: Modify accessibility concerns
  client/src/components/CarouselSlider/CarouselSlider.js
  client/src/components/CarouselSlider/CarouselSlider.stories.js
  client/src/components/MountainCard/MountainCard.js
  client/src/components/MountainCard/MountainCard.module.scss
  client/src/components/MountainCard/MountainCard.stories.js
  client/src/containers/Information/Information.js
  client/src/containers/Information/Information.module.scss
  client/src/containers/ReviewCarousel/ReviewCarousel.module.scss
  client/src/pages/HomePage/HomePage.js
Labels: refactor

#184 Add web server URI environment variable
  client/src/api/authAPI.js
  client/src/api/mountainAPI.js
  client/src/api/profileAPI.js
  client/src/api/recruitPostAPI.js
  client/src/api/regularPostAPI.js
Labels: Settings

#186 Fix bug rendering age in profile page and update name of environment variable
  client/src/api/authAPI.js
  client/src/api/mountainAPI.js
  client/src/api/profileAPI.js
  client/src/api/recruitPostAPI.js
  client/src/api/regularPostAPI.js
  client/src/components/ProfileInfoCard/ProfileInfoCard.js
  client/src/containers/RegularPostList/RegularPostList.js
  client/src/pages/Profile/Profile.js
Labels: Small Adjustment, bug

#187 fix: Fix bug infinite rerendering in regular post list
  client/src/containers/RegularPostList/RegularPostList.js
Labels: bug

#189 fix: Fix bug of rendering date in recruit and regular post components
  client/src/components/PostHeading/PostHeading.js
  client/src/components/Tag/Tag.js
  client/src/containers/RecruitForm/RecruitForm.js
  client/src/utils/filterData.js
Labels: bug

#190 update: Add newstyling to Heading component and fix bug in recruit API
  Server/routes/recruitpost.js
  client/src/components/Header/Header.js
  client/src/components/Header/Header.module.scss
Labels: Server, bug, component, style

#191 feat: Modify how recruitees data is sent to frontend
  Server/routes/recruitpost.js
Labels: Server, feature

#192 update: Add features to recruit API
  Server/routes/recruitpost.js
Labels: Server

#193 style: Modify style for the MainPage
  client/src/components/Header/Header.module.scss
  client/src/components/RegularPostCard/RegularPostCard.module.scss
  client/src/containers/Information/Information.js
  client/src/containers/Information/Information.module.scss
  client/src/containers/ReviewCarousel/ReviewCarousel.js
Labels: page, style

#194 Change router name of profile page with recruit post and rename thunk action creator of recruit post
  client/src/api/recruitPostAPI.js
  client/src/containers/RecruitPostDetail/RecruitPostDetail.js
  client/src/redux/modules/recruitPost.js
Labels: Small Adjustment, documentation

#195 storybook: Write storybook for components
  client/.storybook/preview.js
  client/src/components/AreaCategory/AreaCategory.js
  client/src/components/AreaCategory/AreaCategory.stories.js
  client/src/components/Button/Button.js
  client/src/components/Button/Button.stories.js
  client/src/components/Carousel/Carousel.js
  client/src/components/Carousel/Carousel.module.scss
  client/src/components/Carousel/Carousel.stories.js
  client/src/components/CarouselSlider/CarouselSlider.js
  client/src/components/CarouselSlider/CarouselSlider.stories.js
  client/src/components/Footer/Footer.js
  client/src/components/Footer/Footer.module.scss
  client/src/components/Header/Header.js
  client/src/components/Header/Header.stories.js
  client/src/components/HikingLevelSelectButton/HikingLevelSelectButton.js
  client/src/components/HikingLevelSelectButton/HikingLevelSelectButton.stories.js
  client/src/components/Icon/Icon.stories.js
  client/src/components/MenuTab/MenuTab.js
  client/src/components/MenuTab/MenuTab.stories.js
  client/src/components/index.js
Labels: refactor, storybook

#196 Write storybook and restyle main carousels and regular post card
  client/src/components/CarouselSlider/CarouselSlider.module.scss
  client/src/components/Checkbox/Checkbox.js
  client/src/components/GenderSelectButton/GenderSelectButton.js
  client/src/components/GenderSelectButton/GenderSelectButton.stories.js
  client/src/components/Header/Header.js
  client/src/components/HikingLevelSelectButton/HikingLevelSelectButton.js
  client/src/components/HikingLevelSelectButton/HikingLevelSelectButton.stories.js
  client/src/components/LikeButton/LikeButton.js
  client/src/components/MountainCard/MountainCard.module.scss
  client/src/components/PostHeading/PostHeading.js
  client/src/components/PostHeading/PostHeading.stories.js
  client/src/components/ProfileImage/ProfileImage.js
  client/src/components/PublisherInformation/PublisherInformation.js
  client/src/components/PublisherInformation/PublisherInformation.stories.js
  client/src/components/RadioButton/RadioButton.js
  client/src/components/RadioButton/RadioButton.stories.js
  client/src/components/RecruitPostCard/RecruitPostCard.js
  client/src/components/RecruitPostCard/RecruitPostCard.stories.js
  client/src/components/RegionSelectButton/RegionSelectButton.js
  client/src/components/RegionSelectButtonGroup/RegionSelectButtonGroup.js
  client/src/components/RegionSelectButtonGroup/RegionSelectButtonGroup.stories.js
  client/src/components/RegularPostCard/RegularPostCard.js
  client/src/components/RegularPostCard/RegularPostCard.module.scss
  client/src/components/RegularPostCard/RegularPostCard.stories.js
  client/src/components/RoundedBox/RoundedBox.js
  client/src/components/RoundedBox/RoundedBox.stories.js
  client/src/components/StatusOfApplicationBox/StatusOfApplicationBox.js
  client/src/components/StatusOfApplicationBox/StatusOfApplicationBox.stories.js
  client/src/containers/Information/Information.js
  client/src/containers/Information/Information.module.scss
  client/src/containers/MainRecruit/MainRecruit.module.scss
  client/src/containers/MainRecruit/image/mainRecruit2.png
  client/src/containers/RecruitPostDetail/RecruitPostDetail.js
  client/src/containers/RecruitPostList/RecruitPostList.js
  client/src/containers/RegisterForm/RegisterForm.js
  client/src/containers/RegularPostDetail/RegularPostDetail.js
  client/src/pages/Profile/Profile.js
  client/src/utils/propTypeSchema.js
  client/src/utils/validationSchema.js
Labels: Small Adjustment, documentation, storybook, style

#197 storybook: Write storybook.
  client/src/components/FileInput/FileInput.js
  client/src/components/FileInput/FileInput.stories.js
  client/src/components/FormItem/FormItem.stories.js
  client/src/components/Input/Input.js
  client/src/components/Input/Input.module.scss
  client/src/components/Input/Input.stories.js
  client/src/components/NumberInput/NumberInput.js
  client/src/components/NumberInput/NumberInput.stories.js
  client/src/components/RangeSlider/RangeSlider.js
  client/src/components/RangeSlider/RangeSlider.stories.js
  client/src/components/SelectBox/SelectBox.js
  client/src/components/SelectBox/SelectBox.stories.js
  client/src/components/SelectDate/SelectDate.js
  client/src/components/SelectDate/SelectDate.stories.js
  client/src/containers/RecruitForm/RecruitForm.js
  client/src/redux/modules/regularPost.js
Labels: storybook

#198 fix: Fix recruitee profile page problem
  Server/routes/recruitpost.js
Labels: Server, bug

#199 fix: Fix recruitee image not showing bug
  Server/routes/recruitpost.js
Labels: bug

#201 feat: Add Loading component and Fix error in Form Item storybook.
  client/src/components/FormItem/FormItem.stories.js
  client/src/containers/RecruitPostList/RecruitPostList.js
  client/src/containers/RegularPostList/RegularPostList.js
  client/src/pages/Recruit/RecruitCreate.stories.mdx
Labels: storybook, style

#202 Fix toggle apply recruiting thunk action creator for recruit post detail component and add key prop to each carousel slider card
  client/src/components/CarouselSlider/CarouselSlider.js
  client/src/containers/RecruitForm/RecruitForm.js
  client/src/containers/RecruitPostDetail/RecruitPostDetail.js
  client/src/redux/modules/recruitPost.js
Labels: bug

#204 docs: Write README.md
  README.md
Labels: documentation

#205 Fix bug not rendering the hiking level in korean in regular post detail page and change children prop type of button component
  client/src/components/Button/Button.js
  client/src/utils/filterData.js
Labels: bug
