Repository Santa-Application/App, pull requests merged in 2021-05, with the labels that each got.

#206 storybook: Add decorator and fix component storybooks
  .gitignore
  client/.storybook/preview.js
  client/src/components/Header/Header.js
  client/src/components/Header/Header.stories.js
  client/src/components/Navigation/Navigation.stories.js
  client/src/components/ProfileInfoCard/ProfileInfoCard.js
  client/src/components/SearchBox/SearchBox.stories.js
  client/src/redux/store.js
Labels: storybook

#208 Refactor components, fix issues
  client/src/App/App.js
  client/src/components/Checkbox/Checkbox.js
  client/src/components/Footer/Footer.js
  client/src/components/LikeButton/LikeButton.js
  client/src/components/Navigation/Navigation.js
  client/src/components/PostHeading/PostHeading.js
  client/src/components/ProfileImage/ProfileImage.js
  client/src/components/ProfileInfoCard/ProfileInfoCard.js
  client/src/components/RadioButton/RadioButton.js
  client/src/components/RecruitPostCard/RecruitPostCard.js
  client/src/components/RegionSelectButton/RegionSelectButton.js
  client/src/components/RegionSelectButtonGroup/RegionSelectButtonGroup.js
  client/src/components/Textarea/Textarea.js
  client/src/components/UserInformation/UserInformation.js
  client/src/components/UserInformation/UserInformation.module.scss
  client/src/components/UserInformation/UserInformation.stories.js
  client/src/components/index.js
  client/src/containers/RecruitForm/RecruitForm.js
  client/src/containers/RecruitPostDetail/RecruitPostDetail.js
  client/src/containers/RecruitPostList/RecruitPostList.js
  client/src/containers/RegularPostDetail/RegularPostDetail.js
  client/src/containers/RegularPostForm/RegularPostForm.js
  client/src/containers/RegularPostList/RegularPostList.js
  client/src/utils/filterData.js
Labels: bug, refactor

#209 refactor: Change history, match to hook methods
  client/package.json
  client/src/components/FileInput/FileInput.js
  client/src/components/Logo/Logo.js
  client/src/components/MountainInfo/MountainInfo.js
  client/src/components/SelectDate/SelectDate.js
  client/src/components/index.js
  client/src/containers/Information/Information.js
  client/src/containers/MainRecruit/MainRecruit.js
  client/src/containers/MountainOverview/MountainOverview.js
  client/src/containers/RecruitForm/RecruitForm.js
  client/src/containers/RegisterForm/RegisterForm.js
  client/src/containers/SearchMountain/SearchMountain.js
  client/src/containers/SignInForm/SignInForm.js
  client/src/pages/HomePage/HomePage.js
  client/src/pages/Login/Login.js
  client/src/pages/Main/Main.js
  client/src/pages/Mountain/Mountain.js
  client/src/pages/Profile/Profile.js
  client/src/pages/Recruit/RecruitCreate.js
  client/src/pages/Recruit/RecruitDetail.js
  client/src/pages/Recruit/RecruitEdit.js
  client/src/pages/Recruit/RecruitList.js
  client/src/pages/Register/Register.js
  client/src/pages/Regular/RegularCreate.js
  client/src/pages/Regular/RegularDetail.js
  client/src/pages/Regular/RegularEdit.js
  client/src/pages/Regular/RegularList.js
Labels: refactor

#210 Refactor and fix issues
  client/src/components/Navigation/Navigation.js
  client/src/components/index.js
  client/src/containers/RecruitForm/RecruitForm.js
  client/src/containers/RecruitPostDetail/RecruitPostDetail.js
  client/src/containers/RecruitPostList/RecruitPostList.js
  client/src/containers/RegularPostDetail/RegularPostDetail.js
  client/src/containers/RegularPostForm/RegularPostForm.js
  client/src/containers/RegularPostList/RegularPostList.js
  client/src/pages/Mountain/Mountain.js
  client/src/pages/Profile/Profile.js
  client/src/pages/Recruit/RecruitCreate.js
  client/src/pages/Recruit/RecruitCreate.stories.mdx
  client/src/pages/Recruit/RecruitDetail.js
  client/src/pages/Recruit/RecruitEdit.js
  client/src/pages/Recruit/RecruitList.js
  client/src/pages/Regular/RegularCreate.js
  client/src/pages/Regular/RegularDetail.js
  client/src/pages/Regular/RegularEdit.js
  client/src/pages/Regular/RegularList.js
  client/src/utils/index.js
  client/src/utils/path.js
Labels: bug, refactor, utility

#213 Create component, utilities, fix issues and refactor(in progress)
  client/src/App/App.js
  client/src/Hooks/usePostDetail.js
  client/src/Routes/PrivateRoute.js
  client/src/Routes/PublicRoute.js
  client/src/Routes/Routes.js
  client/src/Routes/ScrollToTop.js
  client/src/Routes/index.js
  client/src/api/authAPI.js
  client/src/api/mountainAPI.js
  client/src/api/profileAPI.js
  client/src/api/recruitPostAPI.js
  client/src/api/regularPostAPI.js
  client/src/components/CreatePostButton/CreatePostButton.js
  client/src/components/CreatePostButton/CreatePostButton.module.scss
  client/src/components/Error/Error.js
  client/src/components/Footer/Footer.js
  client/src/components/ProfileImage/ProfileImage.js
  client/src/components/RadioButton/RadioButton.js
  client/src/components/RecruitPostCard/RecruitPostCard.js
  client/src/components/StatusOfApplicationBox/StatusOfApplicationBox.js
  client/src/components/UserInformation/UserInformation.js
  client/src/components/index.js
  client/src/containers/RecruitForm/RecruitForm.js
  client/src/containers/RecruitPostDetail/RecruitPostDetail.js
  client/src/containers/RecruitPostList/RecruitPostList.js
  client/src/containers/RegularPostDetail/RegularPostDetail.js
  client/src/containers/RegularPostList/RegularPostList.js
  client/src/pages/HomePage/HomePage.module.scss
  client/src/pages/Main/Main.js
  client/src/pages/Mountain/Mountain.js
  client/src/pages/Profile/Profile.js
  client/src/pages/Register/Register.js
  client/src/redux/modules/recruitPost.js
  client/src/redux/modules/regularPost.js
  client/src/utils/apiUtils.js
  client/src/utils/dataFilteringUtils.js
  client/src/utils/index.js
  client/src/utils/path.js
  client/src/utils/reduxUtils.js
Labels: bug, component, feature, refactor, style, utility

#214 Refactor components
  client/src/Hooks/usePostDetail.js
  client/src/Hooks/usePostList.js
  client/src/containers/RecruitPostDetail/RecruitPostDetail.js
  client/src/containers/RecruitPostList/RecruitPostList.js
  client/src/containers/RegularPostDetail/RegularPostDetail.js
  client/src/containers/RegularPostList/RegularPostList.js
  client/src/redux/modules/recruitPost.js
Labels: refactor, utility

#215 Refactor recruit and regular post form components and set router of redirecting to page not found
  client/src/Routes/Routes.js
  client/src/containers/RecruitForm/RecruitForm.js
  client/src/containers/RegularPostForm/RegularPostForm.js
  client/src/utils/handler/formHandler.js
Labels: refactor, utility

#216 Refactor and fix issue
  client/src/Hooks/usePostDetail.js
  client/src/Hooks/usePostList.js
  client/src/components/CreatePostButton/CreatePostButton.js
  client/src/components/RegularPostCard/RegularPostCard.js
  client/src/containers/RecruitPostForm/RecruitPostForm.js
  client/src/containers/RecruitPostForm/RecruitPostForm.module.scss
  client/src/containers/RecruitPostList/RecruitPostList.js
  client/src/containers/RegularPostDetail/RegularPostDetail.js
  client/src/containers/RegularPostForm/RegularPostForm.js
  client/src/containers/RegularPostList/RegularPostList.js
  client/src/containers/index.js
  client/src/pages/Mountain/Mountain.js
  client/src/pages/Profile/Profile.js
  client/src/pages/Recruit/RecruitCreate.js
  client/src/pages/Recruit/RecruitEdit.js
  client/src/utils/handler/formHandler.js
  client/src/utils/handler/tabhandlers.js
  client/src/utils/index.js
  client/src/utils/pathUtils.js
  client/src/utils/postDateUtils.js
Labels: bug, documentation, refactor

#217 Refactor, fix issues and create page
  client/src/Hooks/index.js
  client/src/Hooks/usePostDetail.js
  client/src/Hooks/usePostForm.js
  client/src/Hooks/usePostList.js
  client/src/Routes/Routes.js
  client/src/api/regularPostAPI.js
  client/src/components/CreatePostButton/CreatePostButton.js
  client/src/components/FileInput/FileInput.js
  client/src/components/FormItem/FormItem.js
  client/src/components/Header/Header.module.scss
  client/src/components/Navigation/Navigation.js
  client/src/components/NumberInput/NumberInput.js
  client/src/components/SearchBox/SearchBox.js
  client/src/components/SelectBox/SelectBox.js
  client/src/components/SelectBox/SelectBox.module.scss
  client/src/containers/RecruitPostDetail/RecruitPostDetail.js
  client/src/containers/RecruitPostForm/RecruitPostForm.js
  client/src/containers/RecruitPostList/RecruitPostList.js
  client/src/containers/RegisterForm/RegisterForm.js
  client/src/containers/RegularPostDetail/RegularPostDetail.js
  client/src/containers/RegularPostForm/RegularPostForm.js
  client/src/containers/RegularPostList/RegularPostList.js
  client/src/containers/ReviewCarousel/ReviewCarousel.js
  client/src/containers/SearchMountain/SearchMountain.js
  client/src/pages/ComingSoonPage/ComingSoonPage.js
  client/src/pages/ComingSoonPage/ComingSoonPage.module.scss
  client/src/pages/index.js
  client/src/redux/modules/recruitPost.js
  client/src/utils/formUtils.js
  client/src/utils/handler/formHandler.js
  client/src/utils/index.js
  client/src/utils/pathUtils.js
Labels: Small Adjustment, bug, documentation, page, refactor, style, utility
